'use server'

import { and, eq } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'

import { db } from '@/lib/db'
import { botRefs, bots } from '@/lib/db/schema'
import { requireWorkspace } from '@/lib/workspace'

function revalidateBot(id: string) { revalidatePath('/'); revalidatePath('/bots'); revalidatePath(`/bots/${id}`) }
function normalizeUrl(raw: string) { let url = raw.trim(); if (url && !/^https?:\/\//i.test(url)) url = `https://${url}`; return url }
async function context(botId: string) { const { workspace } = await requireWorkspace(); const [bot] = await db.select({ id: bots.id }).from(bots).where(and(eq(bots.id, botId), eq(bots.workspaceId, workspace.id))).limit(1); if (!bot) throw new Error('Бот не найден'); return workspace }

export async function addRef(botId: string, url: string, successLimit: number) { const workspace = await context(botId); const value = normalizeUrl(url); if (!value) throw new Error('Укажите целевую ссылку'); await db.insert(botRefs).values({ workspaceId: workspace.id, botId, url: value, successLimit: Math.min(10000, Math.max(1, Math.round(successLimit || 10))), status: 'active' }); revalidateBot(botId); return { ok: true as const } }
export async function importRefs(botId: string, text: string, defaultLimit: number) { const workspace = await context(botId); const fallback = Math.min(10000, Math.max(1, Math.round(defaultLimit || 10))); const rows = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => { const [raw, limitRaw] = line.split(/[,;\t]/).map((p) => p?.trim()); const url = normalizeUrl(raw ?? ''); const parsed = Number.parseInt(limitRaw ?? '', 10); return url ? { workspaceId: workspace.id, botId, url, successLimit: Number.isFinite(parsed) && parsed > 0 ? Math.min(10000, parsed) : fallback, status: 'active' as const } : null }).filter((row): row is NonNullable<typeof row> => Boolean(row)); if (!rows.length) throw new Error('Не найдено ни одной ссылки'); await db.insert(botRefs).values(rows); revalidateBot(botId); return { ok: true as const, added: rows.length } }
export async function deleteRef(botId: string, refId: number) { const workspace = await context(botId); await db.delete(botRefs).where(and(eq(botRefs.id, refId), eq(botRefs.botId, botId), eq(botRefs.workspaceId, workspace.id))); revalidateBot(botId); return { ok: true as const } }
export async function toggleRef(botId: string, refId: number, enabled: boolean) { const workspace = await context(botId); const scope = and(eq(botRefs.id, refId), eq(botRefs.botId, botId), eq(botRefs.workspaceId, workspace.id)); const [ref] = await db.select().from(botRefs).where(scope).limit(1); if (!ref) throw new Error('Реф не найден'); await db.update(botRefs).set({ status: enabled ? (ref.successCount >= ref.successLimit ? 'exhausted' : 'active') : 'disabled' }).where(scope); revalidateBot(botId); return { ok: true as const } }
export async function updateRefLimit(botId: string, refId: number, successLimit: number) { const workspace = await context(botId); const scope = and(eq(botRefs.id, refId), eq(botRefs.botId, botId), eq(botRefs.workspaceId, workspace.id)); const [ref] = await db.select().from(botRefs).where(scope).limit(1); if (!ref) throw new Error('Реф не найден'); const limit = Math.min(10000, Math.max(1, Math.round(successLimit || 1))); await db.update(botRefs).set({ successLimit: limit, status: ref.status === 'disabled' ? 'disabled' : ref.successCount >= limit ? 'exhausted' : 'active' }).where(scope); revalidateBot(botId); return { ok: true as const } }
export async function resetRefCounters(botId: string, refId: number) { const workspace = await context(botId); const scope = and(eq(botRefs.id, refId), eq(botRefs.botId, botId), eq(botRefs.workspaceId, workspace.id)); const [ref] = await db.select().from(botRefs).where(scope).limit(1); if (!ref) throw new Error('Реф не найден'); await db.update(botRefs).set({ successCount: 0, failedCount: 0, lastUsedAt: null, status: ref.status === 'disabled' ? 'disabled' : 'active' }).where(scope); revalidateBot(botId); return { ok: true as const } }
